src/KitapGurmesi.Web/Controllers/BookController.cs
using System.Security.Claims;
using KitapGurmesi.Web.Models.Contexts;
using KitapGurmesi.Web.Models.Entities;
using KitapGurmesi.Web.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace KitapGurmesi.Web.Controllers;

public class BookController : Controller
{
    private readonly ApplicationDbContext _dbContext;
    private readonly UserManager<AppUser> _userManager;

    public BookController(ApplicationDbContext dbContext, UserManager<AppUser> userManager)
    {
        _dbContext = dbContext;
        _userManager = userManager;
    }

    [HttpGet]
    public async Task<IActionResult> IndexWithoutCategory()
    {
        var categoryResult = await _dbContext.Categories
            .Include(i => i.Books)
            .ThenInclude(book => book.Author)
            .Select(s => new BookListByCategoryVM
            {
                CategoryName = s.Name,
                BookAndAuthors = s.Books.Select(ss => new BookAndAuthor { Book = ss, Author = ss.Author }).ToList()
            })
            .ToListAsync();

        return View(categoryResult);
    }
    
    [HttpGet]
    public async Task<IActionResult> Index(string id)
    {
        var categoryResult = await _dbContext.Categories
            .Include(i => i.Books)
            .ThenInclude(book => book.Author)
            .Where(p => p.CategoryGuid.Equals(Guid.Parse(id)))
            .Select(s => new BookListByCategoryVM
            {
                CategoryName = s.Name,
                BookAndAuthors = s.Books.Select(ss => new BookAndAuthor { Book = ss, Author = ss.Author }).ToList()
            })
            .FirstOrDefaultAsync();

        return View(categoryResult);
    }

    [HttpGet, Authorize(Roles = "Admin,Editor")]
    public async Task<IActionResult> BookAdd()
    {
        ViewBag.CategoryList = await _dbContext.Categories.ToListAsync();
        ViewBag.AuthorList = await _dbContext.Authors.ToListAsync();
        
        return View();
    }
    
    [HttpPost, Authorize(Roles = "Admin,Editor")]
    public async Task<IActionResult> BookAdd(BookAddVM model)
    {
        if (ModelState.IsValid)
        {
            var categories = await _dbContext.Categories.Where(p =>
                model.SelectedCategories.Select(s => Guid.Parse(s)).ToList().Contains(p.CategoryGuid)).ToListAsync();

            var author =
                await _dbContext.Authors.FirstOrDefaultAsync(p => p.AuthorGuid == Guid.Parse(model.AuthorGuid));

            var book = new Book
            {
                Name = model.Name,
                Description = model.Description,
                Author = author,
                EanCode = model.EanCode,
                Categories = categories,
                CreatedDate = DateTime.Now,
                CreatedUserGuid = Guid.Parse(User.Claims.FirstOrDefault(p => p.Type == ClaimTypes.NameIdentifier).Value)
            };

            _dbContext.Books.Add(book);

            await _dbContext.SaveChangesAsync();

            return RedirectToAction("Index", "Home");
        }
        
        ViewBag.CategoryList = await _dbContext.Categories.ToListAsync();
        ViewBag.AuthorList = await _dbContext.Authors.ToListAsync();
        return View(model);
    }
    
    [HttpGet]
    public async Task<IActionResult> BookDetails(string id)
    {
        var bookResult = await _dbContext.Books.Include(i => i.Author)
            .Include(c => c.Categories)
            .Include(comment => comment.Comments)
            .ThenInclude(bookAppUser => bookAppUser.AppUser)
            .FirstOrDefaultAsync(p => p.BookGuid.Equals(Guid.Parse(id)));

        return View(bookResult);
    }

    [HttpPost, Authorize]
    public async Task<IActionResult> BookCommentAdd(string id, BookCommentAddVM model)
    {
        try
        {
            if (ModelState.IsValid)
            {
                if (id != model?.BookGuid)
                    return RedirectToAction("BookDetails", new { id = model.BookGuid });

                var bookResult =
                    await _dbContext.Books.FirstOrDefaultAsync(p => p.BookGuid == Guid.Parse(model.BookGuid));

                if (bookResult is null)
                    return RedirectToAction("BookDetails", new { id = model.BookGuid });

                var book = await _dbContext.Books.FirstOrDefaultAsync(p => p.BookGuid == Guid.Parse(id));

                var user = await _userManager.FindByIdAsync(User.Claims
                    .FirstOrDefault(p => p.Type == ClaimTypes.NameIdentifier).Value);

                var comment = new Comment
                {
                    Book = book,
                    CreatedDate = DateTime.Now,
                    CommentGuid = Guid.NewGuid(),
                    CommentHeader = model.CommentHeader,
                    CommentStr = model.CommentStr,
                    AppUser = user
                };

                await _dbContext.Comments.AddAsync(comment);

                await _dbContext.SaveChangesAsync();

                return RedirectToAction("BookDetails", new { id = model.BookGuid });
            }
        }
        catch (Exception e)
        {
            Console.WriteLine(e);
            throw;
        }

        return RedirectToAction("BookDetails", routeValues: id);
    }

    [HttpGet, Authorize]
    public async Task<IActionResult> BookCommentDelete(string id)
    {
        if (string.IsNullOrWhiteSpace(id))
            return RedirectToAction("Index");

        var arr = id.Split("--");

        var comment = await _dbContext.Comments.FirstOrDefaultAsync(p => p.CommentGuid == Guid.Parse(arr[0]));

        _dbContext.Remove(comment);

        await _dbContext.SaveChangesAsync();

        return RedirectToAction("BookDetails", new { id = arr[1] });
    }

    [HttpGet, Authorize]
    public async Task<IActionResult> CommentsList(string id)
    {
        var commentsResult = await _dbContext.Comments
            .Include(u => u.AppUser)
            .Include(b => b.Book)
            .ThenInclude(c => c.Categories)
            .Where(p => p.AppUser.Id == id)
            .Select(s => new CommentListByAppUserIdVM
            {
                CategoryName = string.Join(" | ", s.Book.Categories.Select(ss => ss.Name).ToList()),
                Comment = s,
                BookGuid = s.Book.BookGuid.ToString()
            }).OrderByDescending(o => o.Comment.Id)
            .ToListAsync();

        return View(commentsResult);
    }
}

src/KitapGurmesi.Web/ViewComponents/CategoryViewComponent.cs
using KitapGurmesi.Web.Models.Contexts;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace KitapGurmesi.Web.ViewComponents;

public class CategoryViewComponent : ViewComponent
{
    private readonly ApplicationDbContext _dbContext;
    
    public CategoryViewComponent(ApplicationDbContext dbContext)
    {
        _dbContext = dbContext;
    }
    
    // http-s://stackoverflow.com/questions/69245954/i-get-this-error-when-i-use-view-component
    public async Task<IViewComponentResult> InvokeAsync()
    {
        var categoryListResult = await _dbContext.Categories.OrderBy(o => o.Id).ToListAsync();
        
        return View("~/Views/Shared/Components/Books/Category.cshtml", categoryListResult);
    }
}

src/KitapGurmesi.Web/Views/Shared/_Layout.cshtml
@using System.Security.Claims
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - KitapGurmesi.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/KitapGurmesi.Web.styles.css" asp-append-version="true"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container">
            <a class="navbar-brand fw-bold" asp-area="" asp-controller="Home" asp-action="Index">Kitap Gurmesi</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    @* <li class="nav-item"> *@
                    @*     <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Anasayfa</a> *@
                    @* </li> *@
                </ul>
            </div>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1 justify-content-end">
                    @if (false == User.Identity?.IsAuthenticated)
                    {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="SignUp">Üye Ol</a>
                        </li>
                        <li class="nav-item bg-black rounded-3">
                            <a class="nav-link text-light fw-bold" asp-area="" asp-controller="Account" asp-action="Login">Giriş Yap</a>
                        </li>
                    }
                    else
                    {
                        <li class="nav-item">
                            <span class="nav-link text-dark">Merhaba, <strong>@User.Identity.Name</strong></span>
                        </li>

                        <li class="nav-item bg-danger rounded-3">
                            <a class="nav-link text-light fw-bold" asp-area="" asp-controller="Account" asp-action="Logout">Çıkış Yap</a>
                        </li>
                    }
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <div class="row">
        <div class="col-3">
            @if (true == User.Identity?.IsAuthenticated)
            {
                <div class="card" style="width: 18rem;">
                    <div class="card-header bg-secondary text-light">
                        <strong>Yönetim</strong>
                    </div>
                    <div class="list-group list-group-flush">
                        @if (User.IsInRole("Admin"))
                        {
                            <a asp-controller="Manager" asp-action="Index" class="list-group-item list-group-item-action">Kullanıcı Listesi</a>
                            <a asp-controller="Manager" asp-action="RoleList" class="list-group-item list-group-item-action">Role Listesi</a>
                            <a asp-controller="Book" asp-action="IndexWithoutCategory" class="list-group-item list-group-item-action">Kitap Listesi</a>
                            @* <a asp-controller="Book" asp-action="CommentsList" class="list-group-item list-group-item-action">Yorumlar</a> *@
                        }
                        else
                        {
                            <a asp-controller="Book" asp-action="CommentsList" asp-route-id="@User.Claims.FirstOrDefault(p => p.Type == ClaimTypes.NameIdentifier).Value" class="list-group-item list-group-item-action">Yorumlarım</a>
                        }
                    </div>
                </div>
                <br/>
            }

            @await Component.InvokeAsync("Category")
            
        </div>
        <main role="main" class="col-9 bg-light p-2 rounded-3 border border-1">
            @RenderBody()
        </main>
    </div>
</div>

<footer class="border-top footer text-muted">
    <div class="container text-center">
        &copy; 2024 - <strong>Kitap Gurmesi</strong> | Kitapların Yorumlarla Zenginleştiği Platform
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>